package progjava.excecao;
public class Exception5 {
    public static void main(String[] args) {
        try {
            System.out.println("OK");
        } finally {
            System.out.println("Saindo do bloco finally");
        }
    }
}